//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelClient.HotelRetrievalServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hotel", Namespace="http://schemas.datacontract.org/2004/07/HotelWCF")]
    [System.SerializableAttribute()]
    public partial class Hotel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotelAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HotelRatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int hotelIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HotelAddress {
            get {
                return this.HotelAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelAddressField, value) != true)) {
                    this.HotelAddressField = value;
                    this.RaisePropertyChanged("HotelAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HotelName {
            get {
                return this.HotelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelNameField, value) != true)) {
                    this.HotelNameField = value;
                    this.RaisePropertyChanged("HotelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HotelRating {
            get {
                return this.HotelRatingField;
            }
            set {
                if ((this.HotelRatingField.Equals(value) != true)) {
                    this.HotelRatingField = value;
                    this.RaisePropertyChanged("HotelRating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int hotelId {
            get {
                return this.hotelIdField;
            }
            set {
                if ((this.hotelIdField.Equals(value) != true)) {
                    this.hotelIdField = value;
                    this.RaisePropertyChanged("hotelId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HotelRetrievalServiceReference1.ISearchHotel")]
    public interface ISearchHotel {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchHotel/GetHotelById", ReplyAction="http://tempuri.org/ISearchHotel/GetHotelByIdResponse")]
        HotelClient.HotelRetrievalServiceReference1.Hotel GetHotelById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchHotel/GetHotelById", ReplyAction="http://tempuri.org/ISearchHotel/GetHotelByIdResponse")]
        System.Threading.Tasks.Task<HotelClient.HotelRetrievalServiceReference1.Hotel> GetHotelByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchHotel/GetAllHotels", ReplyAction="http://tempuri.org/ISearchHotel/GetAllHotelsResponse")]
        HotelClient.HotelRetrievalServiceReference1.Hotel[] GetAllHotels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchHotel/GetAllHotels", ReplyAction="http://tempuri.org/ISearchHotel/GetAllHotelsResponse")]
        System.Threading.Tasks.Task<HotelClient.HotelRetrievalServiceReference1.Hotel[]> GetAllHotelsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISearchHotelChannel : HotelClient.HotelRetrievalServiceReference1.ISearchHotel, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchHotelClient : System.ServiceModel.ClientBase<HotelClient.HotelRetrievalServiceReference1.ISearchHotel>, HotelClient.HotelRetrievalServiceReference1.ISearchHotel {
        
        public SearchHotelClient() {
        }
        
        public SearchHotelClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearchHotelClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchHotelClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchHotelClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HotelClient.HotelRetrievalServiceReference1.Hotel GetHotelById(int id) {
            return base.Channel.GetHotelById(id);
        }
        
        public System.Threading.Tasks.Task<HotelClient.HotelRetrievalServiceReference1.Hotel> GetHotelByIdAsync(int id) {
            return base.Channel.GetHotelByIdAsync(id);
        }
        
        public HotelClient.HotelRetrievalServiceReference1.Hotel[] GetAllHotels() {
            return base.Channel.GetAllHotels();
        }
        
        public System.Threading.Tasks.Task<HotelClient.HotelRetrievalServiceReference1.Hotel[]> GetAllHotelsAsync() {
            return base.Channel.GetAllHotelsAsync();
        }
    }
}
